package com.news.crimson.model;

public enum NewsCategory {

	WORLD("CAAqKggKIiRDQkFTRlFvSUwyMHZNRGx1YlY4U0JXVnVMVWRDR2dKRFFTZ0FQAQ"),
	LOCAL("CAAqHAgKIhZDQklTQ2pvSWJHOWpZV3hmZGpJb0FBUAE"),
	BUSINESS("CAAqKggKIiRDQkFTRlFvSUwyMHZNRGx6TVdZU0JXVnVMVWRDR2dKRFFTZ0FQAQ"),
	TECHNOLOGY("CAAqKggKIiRDQkFTRlFvSUwyMHZNRGRqTVhZU0JXVnVMVWRDR2dKRFFTZ0FQAQ"),
	ENTERTAINMENT("CAAqKggKIiRDQkFTRlFvSUwyMHZNREpxYW5RU0JXVnVMVWRDR2dKRFFTZ0FQAQ"),
	SPORTS("CAAqKggKIiRDQkFTRlFvSUwyMHZNRFp1ZEdvU0JXVnVMVWRDR2dKRFFTZ0FQAQ"),
	SCIENCE("CAAqKggKIiRDQkFTRlFvSUwyMHZNRFp0Y1RjU0JXVnVMVWRDR2dKRFFTZ0FQAQ"),
	HEALTH("CAAqJQgKIh9DQkFTRVFvSUwyMHZNR3QwTlRFU0JXVnVMVWRDS0FBUAE");
	
	private final String categoryValue;

	private NewsCategory(String value) {
		this.categoryValue = value;
	}
	
	public String getCategoryValue() {
		return this.categoryValue;
	}
}
